"""empty message

Revision ID: 01813008e82c
Revises: 
Create Date: 2018-04-02 03:51:12.583697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01813008e82c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('credit_account',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('customer_uuid', postgresql.UUID(), nullable=False),
    sa.Column('time_opened', sa.TIMESTAMP(), nullable=True),
    sa.Column('apr', sa.Integer(), nullable=True),
    sa.Column('max_credit', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['customer_uuid'], ['customer.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('balance',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('credit_account_uuid', postgresql.UUID(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('available_credit', sa.BIGINT(), nullable=True),
    sa.Column('principal_owed', sa.BIGINT(), nullable=True),
    sa.Column('interest_owed', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['credit_account_uuid'], ['credit_account.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_balance_time', 'balance', ['time'], unique=False)
    op.create_table('payment',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('credit_account_uuid', postgresql.UUID(), nullable=False),
    sa.Column('amount', sa.BIGINT(), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['credit_account_uuid'], ['credit_account.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('withdrawal',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('credit_account_uuid', postgresql.UUID(), nullable=False),
    sa.Column('amount', sa.BIGINT(), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['credit_account_uuid'], ['credit_account.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawal')
    op.drop_table('payment')
    op.drop_index('idx_balance_time', table_name='balance')
    op.drop_table('balance')
    op.drop_table('credit_account')
    op.drop_table('customer')
    # ### end Alembic commands ###
